### ISSUE TITLE
Unclear on how to set things up with respect to cross compiled artifacts

### ISSUE THREAD

**Issue by VorpalBlade** [jaemk/self_update#107]
The documentation mentions that expected layout is compatible with "trust", which seems to be a dead set of scripts for Travis CI (which doesn't seem to be a thing for open source any more).

* Is there anywhere some more concrete documentation of the expected binary names in a release? I will have need for multiple OSes and architectures (e.g. Linux x86-64, Linux ARMv7 hardfloat, Linux ARMv6 non-hardfloat, Mac OS Aarch64, Mac OS x86-64, ...) I assume this looks for something lke: `<base binary name>-<host-triplet>`? But it would be good if this was documented somewhere.
* How can I adjust the naming scheme this crate expects if it doesn't line up with what the CI tooling I use produces? I plan on using https://github.com/taiki-e/upload-rust-binary-action with cross compilation for my CI solution.

**Comment by jaemk** [comment]
Hey @VorpalBlade , I've been meaning to update the docs to show some examples GitHub actions builds, but haven't had the time. The expected release name format can be seen in the releases of this repo https://github.com/jaemk/self_update/releases which is what the runnable examples pull artifacts from

**Comment by jaemk** [comment]
It looks like that tool produces artifacts like $bin-$target.tar.gz, but self update expects $bin-$version-$target.tar.gz in order to know if the latest is actually an update and is compatible. You might be able to configure the builds to include a version in the name. If you can't then, you are also able to use the individual self update structs to do each step (download, unpack, move/replace) instead of using the all-in-one handlers (where you just tell it a GitHub repo)
